## ----------------------------------------------------------------------------
## nexus | NEW.config.mac
##
## Configuration macro to simulate Bi-214 radioactive decays from the dice
## boards in the NEW detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/Generator/IonGenerator/atomic_number 95
/Generator/IonGenerator/mass_number 241
/Generator/IonGenerator/region doesntmatter

#/gps/particle ion
#/gps/ion 82 210 0 0
#/gps/energy 0. eV
#/grdm/nucleusLimits 240 250 94 96
/Actions/DefaultEventAction/min_energy 1 keV

/PhysicsList/Nexus/clustering          false
/PhysicsList/Nexus/drift               false
/PhysicsList/Nexus/electroluminescence false
/PhysicsList/Nexus/photoelectric       false

/nexus/persistency/event_type background
/nexus/persistency/output_file deleteme.next

/process/em/verbose 0
#/process/had/rdm/nucleusLimits 240 250 94 96
