## ----------------------------------------------------------------------------
## nexus | NEXT100_full.config.mac
##
## Configuration macro to simulate Kr-83 decays in the NEXT-100 geometry
## with generation and transportation of optical photons.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
/Geometry/Next100/elfield false
/Geometry/Next100/pressure 5. bar
#/Geometry/Next100/max_step_size 1. mm

##### GENERATOR #####
/Generator/ScintGenerator/region S2_SIPM_PSF
/Generator/ScintGenerator/nphotons 250000

/Actions/SaveAllSteppingAction/select_particle opticalphoton
/Actions/SaveAllSteppingAction/select_volume SIPM_BOARD_MASK_WLS_HOLE
/Actions/SaveAllSteppingAction/select_volume SIPM_BOARD_MASK_WLS
/Actions/SaveAllSteppingAction/select_volume TP_COPPER_PLATE
/Actions/SaveAllSteppingAction/kill_after_selection true

##### PERSISTENCY #####
/nexus/persistency/output_file Next100_kr_full.next
