## ----------------------------------------------------------------------------
## nexus | NEXT100_full.config.mac
##
## Configuration macro to simulate Kr-83 decays in the NEXT-100 geometry
## with generation and transportation of optical photons.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
/Geometry/Next100/elfield true
/Geometry/Next100/EL_field 8.5 kV/cm
/Geometry/Next100/pressure 5. bar
/Geometry/Next100/sc_yield 25510. 1/MeV
/Geometry/Next100/e_lifetime 1000. ms

##### GENERATOR #####
/Generator/Kr83mGenerator/region ACTIVE

/Actions/SaveAllSteppingAction/select_particle opticalphoton
/Actions/SaveAllSteppingAction/select_volume SIPM_BOARD_MASK_WLS_HOLE
/Actions/SaveAllSteppingAction/select_volume SIPM_BOARD_MASK_WLS
/Actions/SaveAllSteppingAction/select_volume TP_COPPER_PLATE
/Actions/SaveAllSteppingAction/kill_after_selection true

##### PERSISTENCY #####
/nexus/persistency/output_file Next100_kr_full.next
/nexus/random_seed 123456789
