### --------------------------------------------------------
###  CLUSTER configuration macro for the square optical fiber geometry.
###  This macro simulates a 172 nm (7.21 eV) optical photon.
###  in the active volume.
### --------------------------------------------------------


/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0


### Generation
/Generator/SingleParticle/particle opticalphoton
/Generator/SingleParticle/min_energy  7.21 eV
/Generator/SingleParticle/max_energy 7.21 eV


/Generator/SingleParticle/region LINE_SOURCE_EL

/Generator/SingleParticle/min_costheta 0
/Generator/SingleParticle/max_costheta 1



#### SETUP PARAMETERS, Big run #### 
/nexus/random_seed ${seed}
/Geometry/SquareOpticalFiber/specific_vertex ${x} ${y} -0.0023 mm # z-value not relevant here in "LINE_SOURCE_EL" mode
/Geometry/SquareOpticalFiber/ELGap ${ELGap} mm
/Geometry/SquareOpticalFiber/pitch ${pitch} mm
/Geometry/SquareOpticalFiber/distanceFiberHolder ${distanceFiberHolder} mm
/Geometry/SquareOpticalFiber/distanceAnodeHolder ${distanceAnodeHolder} mm
/Geometry/SquareOpticalFiber/holderThickness ${holderThickness} mm
/Geometry/SquareOpticalFiber/TPBThickness ${TPBThickness} um 

/SquareOpticalFiber/SquareFiberSD/Output/sipmPath ${sipmOutputFile_}
#/SquareOpticalFiber/SquareFiberSD/Output/tpbPath /dev/null
/SquareOpticalFiber/SquareFiberSD/Output/tpbPath ${tpbOutputFile_}