### --------------------------------------------------------
###  Configuration macro for the square optical fiber geometry.
###  This macro simulates a 172 nm (7.21 eV) optical photon.
###  in the active volume.
### --------------------------------------------------------


/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/em/verbose 0


### Generation
/Generator/SingleParticle/particle opticalphoton
#/Generator/SingleParticle/particle geantino

/Generator/SingleParticle/min_energy 7.21 eV
/Generator/SingleParticle/max_energy 7.21 eV
#/Generator/SingleParticle/min_energy 2.87 eV
#/Generator/SingleParticle/max_energy 2.87 eV

/Geometry/SquareOpticalFiber/holder     true
/Geometry/SquareOpticalFiber/fiber_tpb  true
/Geometry/SquareOpticalFiber/holder_tpb false

/Geometry/SquareOpticalFiber/n_sipms 1
/Geometry/SquareOpticalFiber/sipm_size 3 mm
/Geometry/SquareOpticalFiber/fiber_length 70 mm
/Geometry/SquareOpticalFiber/el_gap_length 10 mm
/Geometry/SquareOpticalFiber/pitch 15.6 mm
/Geometry/SquareOpticalFiber/d_fiber_holder -5 mm
/Geometry/SquareOpticalFiber/d_anode_holder 10 mm
/Geometry/SquareOpticalFiber/holder_thickness 10 mm
/Geometry/SquareOpticalFiber/tpb_thickness 2.2 um
/Geometry/SquareOpticalFiber/tpb_surface_roughness 1e-2
/Geometry/SquareOpticalFiber/coating_reflectivity 0.98

#/tracking/verbose 2


## Choose region
#/Generator/SingleParticle/region FIBER_ENTRY
#Generator/SingleParticle/region AD_HOC
#/Geometry/SquareOpticalFiber/specific_vertex 0 0 -1
/Generator/SingleParticle/region TPB_ENTRY_OUTSIDE
#/Generator/SingleParticle/region FACE_RANDOM_DIST
#/Generator/SingleParticle/region LINE_SOURCE_EL
#/Generator/SingleParticle/region LINE_SOURCE_EL_TRANSVERSE_DIFFUSION


/Generator/SingleParticle/min_costheta 0
/Generator/SingleParticle/max_costheta 1


####  SETUP PARAMETERS  ####
/nexus/random_seed 10002

#/Geometry/SquareOpticalFiber/specific_vertex 0 0 0 mm #  For LINE_SOURCE_EL variants

## Write output hitpoint text files ##
/Geometry/SquareOpticalFiber/sipm_path sipm_hits.txt
/Geometry/SquareOpticalFiber/tpb_path tpb_hits.txt
#/nexus/persistency/outputFile out.nexus

#/Actions/SaveAllSteppingAction/select_volume SiPM
#/Actions/SaveAllSteppingAction/select_volume TPB
#/Actions/SaveAllSteppingAction/select_volume WORLD
#/Actions/SaveAllSteppingAction/select_volume Cap1
#/Actions/SaveAllSteppingAction/select_volume Barrel
